# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 05:07
from __future__ import unicode_literals

import core.oauth2client.django_orm
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appinfo', '0004_auto_20160614_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='admob_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', core.oauth2client.django_orm.CredentialsField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='adtech_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=256, null=True)),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chartboost_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('user_id', models.CharField(max_length=50, null=True)),
                ('signature', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='facebook_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='foreign_ids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100, null=True)),
                ('foreign_id', models.CharField(max_length=100, null=True)),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_ids', to='appinfo.AppInfo')),
                ('platform_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foreign_ids', to='ad_revenues.credentials')),
            ],
        ),
    ]
