# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(serialize=False, primary_key=True)),
                ('name', models.CharField(unique=True, max_length=255, db_index=True)),
                ('alpha2', models.CharField(unique=True, max_length=2, db_index=True)),
                ('alpha3', models.CharField(unique=True, max_length=3, db_index=True)),
                ('numeric', models.CharField(unique=True, max_length=3, db_index=True)),
            ],
            options={
                'db_table': 'countries',
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
            bases=(models.Model,),
        ),
        migrations.RunSQL(
            sql="""
                INSERT INTO countries
                    (`creation_time`, `last_modified`, `name`, `alpha2`, `alpha3`, `numeric`)
                VALUES
                    (now(), now(), 'Afghanistan', 'AF', 'AFG', '004'),
                    (now(), now(), 'Åland Islands', 'AX', 'ALA', '248'),
                    (now(), now(), 'Albania', 'AL', 'ALB', '008'),
                    (now(), now(), 'Algeria', 'DZ', 'DZA', '012'),
                    (now(), now(), 'American Samoa', 'AS', 'ASM', '016'),
                    (now(), now(), 'Andorra', 'AD', 'AND', '020'),
                    (now(), now(), 'Angola', 'AO', 'AGO', '024'),
                    (now(), now(), 'Anguilla', 'AI', 'AIA', '660'),
                    (now(), now(), 'Antarctica', 'AQ', 'ATA', '010'),
                    (now(), now(), 'Antigua and Barbuda', 'AG', 'ATG', '028'),
                    (now(), now(), 'Argentina', 'AR', 'ARG', '032'),
                    (now(), now(), 'Armenia', 'AM', 'ARM', '051'),
                    (now(), now(), 'Aruba', 'AW', 'ABW', '533'),
                    (now(), now(), 'Australia', 'AU', 'AUS', '036'),
                    (now(), now(), 'Austria', 'AT', 'AUT', '040'),
                    (now(), now(), 'Azerbaijan', 'AZ', 'AZE', '031'),
                    (now(), now(), 'Bahamas', 'BS', 'BHS', '044'),
                    (now(), now(), 'Bahrain', 'BH', 'BHR', '048'),
                    (now(), now(), 'Bangladesh', 'BD', 'BGD', '050'),
                    (now(), now(), 'Barbados', 'BB', 'BRB', '052'),
                    (now(), now(), 'Belarus', 'BY', 'BLR', '112'),
                    (now(), now(), 'Belgium', 'BE', 'BEL', '056'),
                    (now(), now(), 'Belize', 'BZ', 'BLZ', '084'),
                    (now(), now(), 'Benin', 'BJ', 'BEN', '204'),
                    (now(), now(), 'Bermuda', 'BM', 'BMU', '060'),
                    (now(), now(), 'Bhutan', 'BT', 'BTN', '064'),
                    (now(), now(), 'Bolivia, Plurinational State of', 'BO', 'BOL', '068'),
                    (now(), now(), 'Bonaire, Sint Eustatius and Saba', 'BQ', 'BES', '535'),
                    (now(), now(), 'Bosnia and Herzegovina', 'BA', 'BIH', '070'),
                    (now(), now(), 'Botswana', 'BW', 'BWA', '072'),
                    (now(), now(), 'Bouvet Island', 'BV', 'BVT', '074'),
                    (now(), now(), 'Brazil', 'BR', 'BRA', '076'),
                    (now(), now(), 'British Indian Ocean Territory', 'IO', 'IOT', '086'),
                    (now(), now(), 'Brunei Darussalam', 'BN', 'BRN', '096'),
                    (now(), now(), 'Bulgaria', 'BG', 'BGR', '100'),
                    (now(), now(), 'Burkina Faso', 'BF', 'BFA', '854'),
                    (now(), now(), 'Burundi', 'BI', 'BDI', '108'),
                    (now(), now(), 'Cabo Verde', 'CV', 'CPV', '132'),
                    (now(), now(), 'Cambodia', 'KH', 'KHM', '116'),
                    (now(), now(), 'Cameroon', 'CM', 'CMR', '120'),
                    (now(), now(), 'Canada', 'CA', 'CAN', '124'),
                    (now(), now(), 'Cayman Islands', 'KY', 'CYM', '136'),
                    (now(), now(), 'Central African Republic', 'CF', 'CAF', '140'),
                    (now(), now(), 'Chad', 'TD', 'TCD', '148'),
                    (now(), now(), 'Chile', 'CL', 'CHL', '152'),
                    (now(), now(), 'China', 'CN', 'CHN', '156'),
                    (now(), now(), 'Christmas Island', 'CX', 'CXR', '162'),
                    (now(), now(), 'Cocos (Keeling) Islands', 'CC', 'CCK', '166'),
                    (now(), now(), 'Colombia', 'CO', 'COL', '170'),
                    (now(), now(), 'Comoros', 'KM', 'COM', '174'),
                    (now(), now(), 'Congo', 'CG', 'COG', '178'),
                    (now(), now(), 'Congo, the Democratic Republic of the', 'CD', 'COD', '180'),
                    (now(), now(), 'Cook Islands', 'CK', 'COK', '184'),
                    (now(), now(), 'Costa Rica', 'CR', 'CRI', '188'),
                    (now(), now(), 'Côte d''Ivoire', 'CI', 'CIV', '384'),
                    (now(), now(), 'Croatia', 'HR', 'HRV', '191'),
                    (now(), now(), 'Cuba', 'CU', 'CUB', '192'),
                    (now(), now(), 'Curaçao', 'CW', 'CUW', '531'),
                    (now(), now(), 'Cyprus', 'CY', 'CYP', '196'),
                    (now(), now(), 'Czech Republic', 'CZ', 'CZE', '203'),
                    (now(), now(), 'Denmark', 'DK', 'DNK', '208'),
                    (now(), now(), 'Djibouti', 'DJ', 'DJI', '262'),
                    (now(), now(), 'Dominica', 'DM', 'DMA', '212'),
                    (now(), now(), 'Dominican Republic', 'DO', 'DOM', '214'),
                    (now(), now(), 'Ecuador', 'EC', 'ECU', '218'),
                    (now(), now(), 'Egypt', 'EG', 'EGY', '818'),
                    (now(), now(), 'El Salvador', 'SV', 'SLV', '222'),
                    (now(), now(), 'Equatorial Guinea', 'GQ', 'GNQ', '226'),
                    (now(), now(), 'Eritrea', 'ER', 'ERI', '232'),
                    (now(), now(), 'Estonia', 'EE', 'EST', '233'),
                    (now(), now(), 'Ethiopia', 'ET', 'ETH', '231'),
                    (now(), now(), 'Falkland Islands (Malvinas)', 'FK', 'FLK', '238'),
                    (now(), now(), 'Faroe Islands', 'FO', 'FRO', '234'),
                    (now(), now(), 'Fiji', 'FJ', 'FJI', '242'),
                    (now(), now(), 'Finland', 'FI', 'FIN', '246'),
                    (now(), now(), 'France', 'FR', 'FRA', '250'),
                    (now(), now(), 'French Guiana', 'GF', 'GUF', '254'),
                    (now(), now(), 'French Polynesia', 'PF', 'PYF', '258'),
                    (now(), now(), 'French Southern Territories', 'TF', 'ATF', '260'),
                    (now(), now(), 'Gabon', 'GA', 'GAB', '266'),
                    (now(), now(), 'Gambia', 'GM', 'GMB', '270'),
                    (now(), now(), 'Georgia', 'GE', 'GEO', '268'),
                    (now(), now(), 'Germany', 'DE', 'DEU', '276'),
                    (now(), now(), 'Ghana', 'GH', 'GHA', '288'),
                    (now(), now(), 'Gibraltar', 'GI', 'GIB', '292'),
                    (now(), now(), 'Greece', 'GR', 'GRC', '300'),
                    (now(), now(), 'Greenland', 'GL', 'GRL', '304'),
                    (now(), now(), 'Grenada', 'GD', 'GRD', '308'),
                    (now(), now(), 'Guadeloupe', 'GP', 'GLP', '312'),
                    (now(), now(), 'Guam', 'GU', 'GUM', '316'),
                    (now(), now(), 'Guatemala', 'GT', 'GTM', '320'),
                    (now(), now(), 'Guernsey', 'GG', 'GGY', '831'),
                    (now(), now(), 'Guinea', 'GN', 'GIN', '324'),
                    (now(), now(), 'Guinea-Bissau', 'GW', 'GNB', '624'),
                    (now(), now(), 'Guyana', 'GY', 'GUY', '328'),
                    (now(), now(), 'Haiti', 'HT', 'HTI', '332'),
                    (now(), now(), 'Heard Island and McDonald Islands', 'HM', 'HMD', '334'),
                    (now(), now(), 'Holy See (Vatican City State)', 'VA', 'VAT', '336'),
                    (now(), now(), 'Honduras', 'HN', 'HND', '340'),
                    (now(), now(), 'Hong Kong', 'HK', 'HKG', '344'),
                    (now(), now(), 'Hungary', 'HU', 'HUN', '348'),
                    (now(), now(), 'Iceland', 'IS', 'ISL', '352'),
                    (now(), now(), 'India', 'IN', 'IND', '356'),
                    (now(), now(), 'Indonesia', 'ID', 'IDN', '360'),
                    (now(), now(), 'Iran, Islamic Republic of', 'IR', 'IRN', '364'),
                    (now(), now(), 'Iraq', 'IQ', 'IRQ', '368'),
                    (now(), now(), 'Ireland', 'IE', 'IRL', '372'),
                    (now(), now(), 'Isle of Man', 'IM', 'IMN', '833'),
                    (now(), now(), 'Israel', 'IL', 'ISR', '376'),
                    (now(), now(), 'Italy', 'IT', 'ITA', '380'),
                    (now(), now(), 'Jamaica', 'JM', 'JAM', '388'),
                    (now(), now(), 'Japan', 'JP', 'JPN', '392'),
                    (now(), now(), 'Jersey', 'JE', 'JEY', '832'),
                    (now(), now(), 'Jordan', 'JO', 'JOR', '400'),
                    (now(), now(), 'Kazakhstan', 'KZ', 'KAZ', '398'),
                    (now(), now(), 'Kenya', 'KE', 'KEN', '404'),
                    (now(), now(), 'Kiribati', 'KI', 'KIR', '296'),
                    (now(), now(), 'Korea, Democratic People''s Republic of', 'KP', 'PRK', '408'),
                    (now(), now(), 'Korea, Republic of', 'KR', 'KOR', '410'),
                    (now(), now(), 'Kuwait', 'KW', 'KWT', '414'),
                    (now(), now(), 'Kyrgyzstan', 'KG', 'KGZ', '417'),
                    (now(), now(), 'Lao People''s Democratic Republic', 'LA', 'LAO', '418'),
                    (now(), now(), 'Latvia', 'LV', 'LVA', '428'),
                    (now(), now(), 'Lebanon', 'LB', 'LBN', '422'),
                    (now(), now(), 'Lesotho', 'LS', 'LSO', '426'),
                    (now(), now(), 'Liberia', 'LR', 'LBR', '430'),
                    (now(), now(), 'Libya', 'LY', 'LBY', '434'),
                    (now(), now(), 'Liechtenstein', 'LI', 'LIE', '438'),
                    (now(), now(), 'Lithuania', 'LT', 'LTU', '440'),
                    (now(), now(), 'Luxembourg', 'LU', 'LUX', '442'),
                    (now(), now(), 'Macao', 'MO', 'MAC', '446'),
                    (now(), now(), 'Macedonia, the former Yugoslav Republic of', 'MK', 'MKD', '807'),
                    (now(), now(), 'Madagascar', 'MG', 'MDG', '450'),
                    (now(), now(), 'Malawi', 'MW', 'MWI', '454'),
                    (now(), now(), 'Malaysia', 'MY', 'MYS', '458'),
                    (now(), now(), 'Maldives', 'MV', 'MDV', '462'),
                    (now(), now(), 'Mali', 'ML', 'MLI', '466'),
                    (now(), now(), 'Malta', 'MT', 'MLT', '470'),
                    (now(), now(), 'Marshall Islands', 'MH', 'MHL', '584'),
                    (now(), now(), 'Martinique', 'MQ', 'MTQ', '474'),
                    (now(), now(), 'Mauritania', 'MR', 'MRT', '478'),
                    (now(), now(), 'Mauritius', 'MU', 'MUS', '480'),
                    (now(), now(), 'Mayotte', 'YT', 'MYT', '175'),
                    (now(), now(), 'Mexico', 'MX', 'MEX', '484'),
                    (now(), now(), 'Micronesia, Federated States of', 'FM', 'FSM', '583'),
                    (now(), now(), 'Moldova, Republic of', 'MD', 'MDA', '498'),
                    (now(), now(), 'Monaco', 'MC', 'MCO', '492'),
                    (now(), now(), 'Mongolia', 'MN', 'MNG', '496'),
                    (now(), now(), 'Montenegro', 'ME', 'MNE', '499'),
                    (now(), now(), 'Montserrat', 'MS', 'MSR', '500'),
                    (now(), now(), 'Morocco', 'MA', 'MAR', '504'),
                    (now(), now(), 'Mozambique', 'MZ', 'MOZ', '508'),
                    (now(), now(), 'Myanmar', 'MM', 'MMR', '104'),
                    (now(), now(), 'Namibia', 'NA', 'NAM', '516'),
                    (now(), now(), 'Nauru', 'NR', 'NRU', '520'),
                    (now(), now(), 'Nepal', 'NP', 'NPL', '524'),
                    (now(), now(), 'Netherlands', 'NL', 'NLD', '528'),
                    (now(), now(), 'New Caledonia', 'NC', 'NCL', '540'),
                    (now(), now(), 'New Zealand', 'NZ', 'NZL', '554'),
                    (now(), now(), 'Nicaragua', 'NI', 'NIC', '558'),
                    (now(), now(), 'Niger', 'NE', 'NER', '562'),
                    (now(), now(), 'Nigeria', 'NG', 'NGA', '566'),
                    (now(), now(), 'Niue', 'NU', 'NIU', '570'),
                    (now(), now(), 'Norfolk Island', 'NF', 'NFK', '574'),
                    (now(), now(), 'Northern Mariana Islands', 'MP', 'MNP', '580'),
                    (now(), now(), 'Norway', 'NO', 'NOR', '578'),
                    (now(), now(), 'Oman', 'OM', 'OMN', '512'),
                    (now(), now(), 'Pakistan', 'PK', 'PAK', '586'),
                    (now(), now(), 'Palau', 'PW', 'PLW', '585'),
                    (now(), now(), 'Palestine, State of', 'PS', 'PSE', '275'),
                    (now(), now(), 'Panama', 'PA', 'PAN', '591'),
                    (now(), now(), 'Papua New Guinea', 'PG', 'PNG', '598'),
                    (now(), now(), 'Paraguay', 'PY', 'PRY', '600'),
                    (now(), now(), 'Peru', 'PE', 'PER', '604'),
                    (now(), now(), 'Philippines', 'PH', 'PHL', '608'),
                    (now(), now(), 'Pitcairn', 'PN', 'PCN', '612'),
                    (now(), now(), 'Poland', 'PL', 'POL', '616'),
                    (now(), now(), 'Portugal', 'PT', 'PRT', '620'),
                    (now(), now(), 'Puerto Rico', 'PR', 'PRI', '630'),
                    (now(), now(), 'Qatar', 'QA', 'QAT', '634'),
                    (now(), now(), 'Réunion', 'RE', 'REU', '638'),
                    (now(), now(), 'Romania', 'RO', 'ROU', '642'),
                    (now(), now(), 'Russian Federation', 'RU', 'RUS', '643'),
                    (now(), now(), 'Rwanda', 'RW', 'RWA', '646'),
                    (now(), now(), 'Saint Barthélemy', 'BL', 'BLM', '652'),
                    (now(), now(), 'Saint Helena, Ascension and Tristan da Cunha', 'SH', 'SHN', '654'),
                    (now(), now(), 'Saint Kitts and Nevis', 'KN', 'KNA', '659'),
                    (now(), now(), 'Saint Lucia', 'LC', 'LCA', '662'),
                    (now(), now(), 'Saint Martin (French part)', 'MF', 'MAF', '663'),
                    (now(), now(), 'Saint Pierre and Miquelon', 'PM', 'SPM', '666'),
                    (now(), now(), 'Saint Vincent and the Grenadines', 'VC', 'VCT', '670'),
                    (now(), now(), 'Samoa', 'WS', 'WSM', '882'),
                    (now(), now(), 'San Marino', 'SM', 'SMR', '674'),
                    (now(), now(), 'Sao Tome and Principe', 'ST', 'STP', '678'),
                    (now(), now(), 'Saudi Arabia', 'SA', 'SAU', '682'),
                    (now(), now(), 'Senegal', 'SN', 'SEN', '686'),
                    (now(), now(), 'Serbia', 'RS', 'SRB', '688'),
                    (now(), now(), 'Seychelles', 'SC', 'SYC', '690'),
                    (now(), now(), 'Sierra Leone', 'SL', 'SLE', '694'),
                    (now(), now(), 'Singapore', 'SG', 'SGP', '702'),
                    (now(), now(), 'Sint Maarten (Dutch part)', 'SX', 'SXM', '534'),
                    (now(), now(), 'Slovakia', 'SK', 'SVK', '703'),
                    (now(), now(), 'Slovenia', 'SI', 'SVN', '705'),
                    (now(), now(), 'Solomon Islands', 'SB', 'SLB', '090'),
                    (now(), now(), 'Somalia', 'SO', 'SOM', '706'),
                    (now(), now(), 'South Africa', 'ZA', 'ZAF', '710'),
                    (now(), now(), 'South Georgia and the South Sandwich Islands', 'GS', 'SGS', '239'),
                    (now(), now(), 'South Sudan', 'SS', 'SSD', '728'),
                    (now(), now(), 'Spain', 'ES', 'ESP', '724'),
                    (now(), now(), 'Sri Lanka', 'LK', 'LKA', '144'),
                    (now(), now(), 'Sudan', 'SD', 'SDN', '729'),
                    (now(), now(), 'Suriname', 'SR', 'SUR', '740'),
                    (now(), now(), 'Svalbard and Jan Mayen', 'SJ', 'SJM', '744'),
                    (now(), now(), 'Swaziland', 'SZ', 'SWZ', '748'),
                    (now(), now(), 'Sweden', 'SE', 'SWE', '752'),
                    (now(), now(), 'Switzerland', 'CH', 'CHE', '756'),
                    (now(), now(), 'Syrian Arab Republic', 'SY', 'SYR', '760'),
                    (now(), now(), 'Taiwan, Province of China', 'TW', 'TWN', '158'),
                    (now(), now(), 'Tajikistan', 'TJ', 'TJK', '762'),
                    (now(), now(), 'Tanzania, United Republic of', 'TZ', 'TZA', '834'),
                    (now(), now(), 'Thailand', 'TH', 'THA', '764'),
                    (now(), now(), 'Timor-Leste', 'TL', 'TLS', '626'),
                    (now(), now(), 'Togo', 'TG', 'TGO', '768'),
                    (now(), now(), 'Tokelau', 'TK', 'TKL', '772'),
                    (now(), now(), 'Tonga', 'TO', 'TON', '776'),
                    (now(), now(), 'Trinidad and Tobago', 'TT', 'TTO', '780'),
                    (now(), now(), 'Tunisia', 'TN', 'TUN', '788'),
                    (now(), now(), 'Turkey', 'TR', 'TUR', '792'),
                    (now(), now(), 'Turkmenistan', 'TM', 'TKM', '795'),
                    (now(), now(), 'Turks and Caicos Islands', 'TC', 'TCA', '796'),
                    (now(), now(), 'Tuvalu', 'TV', 'TUV', '798'),
                    (now(), now(), 'Uganda', 'UG', 'UGA', '800'),
                    (now(), now(), 'Ukraine', 'UA', 'UKR', '804'),
                    (now(), now(), 'United Arab Emirates', 'AE', 'ARE', '784'),
                    (now(), now(), 'United Kingdom', 'GB', 'GBR', '826'),
                    (now(), now(), 'United States', 'US', 'USA', '840'),
                    (now(), now(), 'United States Minor Outlying Islands', 'UM', 'UMI', '581'),
                    (now(), now(), 'Uruguay', 'UY', 'URY', '858'),
                    (now(), now(), 'Uzbekistan', 'UZ', 'UZB', '860'),
                    (now(), now(), 'Vanuatu', 'VU', 'VUT', '548'),
                    (now(), now(), 'Venezuela, Bolivarian Republic of', 'VE', 'VEN', '862'),
                    (now(), now(), 'Viet Nam', 'VN', 'VNM', '704'),
                    (now(), now(), 'Virgin Islands, British', 'VG', 'VGB', '092'),
                    (now(), now(), 'Virgin Islands, U.S.', 'VI', 'VIR', '850'),
                    (now(), now(), 'Wallis and Futuna', 'WF', 'WLF', '876'),
                    (now(), now(), 'Western Sahara', 'EH', 'ESH', '732'),
                    (now(), now(), 'Yemen', 'YE', 'YEM', '887'),
                    (now(), now(), 'Zambia', 'ZM', 'ZMB', '894'),
                    (now(), now(), 'Zimbabwe', 'ZW', 'ZWE', '716')
                ;
                """,
        ),
    ]
