# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0001_initial'),
    ]

    operations = [
		    
		migrations.RunSQL(
			"""
			CREATE TABLE IF NOT EXISTS `currencies` (
			  `iso_code` varchar(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
			  `usd_conversion_rate` decimal(30,10) NOT NULL,
			  `symbol` varchar(3) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
			  `uni_code` varchar(8) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
			  `position` varchar(6) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
			  `comments` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
			  `display_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
			  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
			  PRIMARY KEY (`iso_code`)
			) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_croatian_ci;
			

			INSERT INTO currencies 
				(iso_code, usd_conversion_rate, symbol, uni_code, position, comments, display_name)
			VALUES
				('AFA','68.42','','','before','','Afghan Afghani'),
				('AFN','68.42','','','before','','Afghan Afghani'),
				('ALL','121.70','Lek','','before','','Albanian Lek'),
				('AOA','162.76','AOA','AOA','before','', 'Angolan Kwanza'),
				('AED','3.67','د.إ','','after','Can not find', 'United Arab Emirates Dirham'),
				('AMD','482.61','֏','&#1423;','after','Can not find', 'Armenian Dram'),
				('ANG','1.79','ƒ','&#x0192;','before','','Netherlands Antillean Guilder'),
				('ARS','14.47','$','&#36;','before','','Argentine Peso'),
				('AUD','1.32','$','&#36;','before','','Australian Dollar'),
				('AWG','1.79','ƒ','','before','','Aruban Florin'),
				('AZN','1.53','ƒ','','before','','Azerbaijani Manat'),
				('BHD','0.38','BD','BD','after','','Bahraini Dinar'),
				('BDT','78.10','','','before','','Bangladeshi Taka'),
				('BBD','2.00','$','&#36;','before','','Barbadian Dollar'),
				('BYR','19980.00','','','before','','Belarusian Ruble'),
				('BEF','35.40','','','before','','Belgian Franc'),
				('BAM','1.72','KM','KM','before','','Bosnia-Herzegovina Convertible Mark'),
				('BGN','1.72','','','before','','Bulgarian Lev'),
				('BIF','1567.30','','','after','','Burundian Franc'),
				('BMD','1.00','','','after','','Bermudan Dollar'),
				('BOB','6.91','','','after','','Bolivian Boliviano'),
				('BRL','3.59','R$','R&#36;','before','','Brazilian Real'),
				('BSD','1.00','','','before','','Bahamian Dollar'),
				('BTC','0.0024','','','before','','Bitcoin'),
				('BTN','66.44','','','before','','Bhutanese Ngultrum'),
				('BWP','10.95','','','before','','Botswanan Pula'),
				('BZD','2.00','','','before','','Belize Dollar'),
				('BND','1.35','$','&#36;','before','','Brunei Dollar'),
				('CAD','1.30','$','&#36;','before','','Canadian Dollar'),
				('CDF','928.00','','','before','','Congolese Franc'),
				('CHF','0.95','Fr','Fr','before','','Swiss Franc'),
				('CLF','0.03','UF','UF','after','','Chilean Unidad de Fomento'),
				('CLP','682.75','$','&#36;','before','','Chilean Peso'),
				('CNY','6.47','¥','&#165;','before','','Chinese Yuan'),
				('COP','3097.15','$','&#36;','before','','Colombian Peso'),
				('CRC','535.27','₡','&#x20A1;','before','','Costa Rican Colón'),
				('CUP','26.50','','','before','','Cuban Peso'),
				('CVE','96.81','','','before','','Cape Verdean Escudo'),
				('CUC','1.00','','','before','','Cuban Convertible Peso'),
				('CZK','23.72','Kč','K&#269;','after','','Czech Republic Koruna'),
				('DJF','177.69','','','before','','Djiboutian Franc'),
				('DKK','6.53','kr','kr','before','','Danish Krone'),
				('DOP','45.91','','','before','','Dominican Peso'),
				('DZD','108.08','kr','kr','before','','Algerian Dinar'),
				('DEM','1.72','','','before','','German Mark'),
				('EEK','11.73','KR','KR','before','','Estonian Kroon'),
				('EGP','8.88','E£','E&#163;','before','','Egyptian Pound'),
				('ERN','16.18','','','before','','Eritrean Nakfa'),
				('ETP','21.50','','','before','','Ethiopian Birr'),
				('EUR','0.88','€','&#128;','before','','Euro'),
				('FJD','2.09','FJ$','FJ&#36;','before','','Fijian Dollar'),
				('FKP','0.66','','','before','','Falkland Islands Pound'),
				('GBP','0.70','£','&#163;','before','','British Pound'),
				('GEL','2.27','','','before','','Georgian Lari'),
				('GMD','42.61','','','before','','Gambian Dalasi'),
				('GHS','3.82','','','before','','Ghanaian Cedi'),
				('GIP','0.69','','','before','','Gibraltar Pound'),
				('GID','297.845','','','before','','Greek Drachma'),
				('GNF','7599.95','','','before','','Guinean Franc'),
				('GIQ','7.73','Q','Q','before','','Guatemalan Quetzal'),
				('GYD','207.21','','','before','','Guyanaese Dollar'),
				('HKD','7.75','$','&#36;','before','','Hong Kong Dollar'),
				('HRK','6.55','kn','kn','before','','Croatian Kuna'),
				('HUF','272.74','Ft','Ft','before','','Hungarian Forint'),
				('HNL','22.61','','','before','','Honduran Lempira'),
				('HTG','61.78','','','before','','Haitian Gourde'),
				('IDR','13110.00','Rp','Rp','before','','Indonesian Rupiah'),
				('ILS','3.77','₪','&#x20AA;','before','','Israeli New Sheqel'),
				('INR','66.34','Rs','Rs','before','There is not a unicode','Indian Rupee'),
				('IMP','0.70','','','before','','Isle of Man Pound'),
				('IQD','1107.10','','','before','','Iraqi Dinar'),
				('IRR','30274.00','','','before','','Iranian Rial'),
				('ISK','122.97','','','before','','Icelandic Króna'),
				('ITL','1709.66','','','before','','Italian Lira'),
				('JOD','0.71','د.ا','','','Can not find','Jordanian Dinar'),
				('JPY','108.05','¥','&#165;','before','','Japanese Yen'),
				('JEP','0.70','','','before','','Jersey Pound'),
				('JMD','121.70','','','before','','Jamaican Dollar'),
				('KES','101.11','KSh','Ksh','before','','Kenyan Shilling'),
				('KRW','1143.88','₩','&#x20A9;','before','','South Korean Won'),
				('KWD','0.30','KD','KD','after','','Kuwaiti Dinar'),
				('KYD','0.82','$','&#36;','before','','Cayman Islands Dollar'),
				('KGS','69.98','','','before','','Kyrgystani Som'),
				('KHR','4042.75','','','before','','Cambodian Riel'),
				('KMF','429.93','','','before','','Comorian Franc'),
				('KPW','130.25','','','before','','North Korean Won'),
				('KZT','336.70','','','before','','Kazakhstani Tenge'),
				('LTL','3.05','Lt','Lt','before','','Lithuanian Litas'),
				('LVL','0.62','Ls','Ls','before','','Latvian Lats'),
				('LAK','8115.45','','','before','','Laotian Kip'),
				('LBP','1508.00','','','before','','Lebanese Pound'),
				('LKR','144.84','','','before','','Sri Lankan Rupee'),
				('LRD','84.67','','','before','','Liberian Dollar'),
				('LSL','14.64','','','before','','Lesotho Loti'),
				('LYD','1.36','','','before','','Libyan Dinar'),
				('MAD','9.61','د.م.','','','Can not find','Moroccan Dirham'),
				('MVR','15.37','Rf','Rf','before','','Maldivian Rufiyaa'),
				('MXN','17.63','$','&#36;','before','','Mexican Peso'),
				('MYR','3.88','RM','RM','before','','Malaysian Ringgit'),
				('MDL','19.63','','','before','','Moldovan Leu'),
				('MGA','3171.45','','','before','','Malagasy Ariary'),
				('MKD','53.81','','','before','','Macedonian Denar'),
				('MMK','1174.90','','','before','','Myanmar Kyat'),
				('MNT','2019.50','','','before','','Mongolian Tugrik'),
				('MOP','7.99','','','before','','Macanese Pataca'),
				('MRO','343.00','','','before','','Mauritanian Ouguiya'),
				('MTL','0.37','','','before','','Maltese Lira'),
				('MUR','35.05','','','before','','Mauritian Rupee'),
				('MWK','684.66','','','before','','Malawian Kwacha'),
				('MZN','52.47','','','before','','Mozambican Metical'),
				('MZM','52479.80','','','before','','Mozambican Metical'),
				('NGN','199.05','₦','&#x20A6;','before','','Nigerian Naira'),
				('NOK','8.20','kr','kr','before','','Norwegian Krone'),
				('NZD','1.46','$','&#36;','before','','New Zealand Dollar'),
				('NAD','14.71','','','before','','Namibian Dollar'),
				('NIO','28.31','','','before','','Nicaraguan Córdoba'),
				('NPR','106.32','','','before','','Nepalese Rupee'),
				('OMR','0.39','OMR','&#65020;','after','Unsure if this is correct','Omani Rial'),
				('PEN','3.28','S/.','S/.','before','','Peruvian Nuevo Sol'),
				('PHP','46.11','₱','&#x20B1;','before','','Philippine Peso'),
				('PLN','3.74','zł','Z&#322;','before','','Polish Zloty'),
				('PAB','1.00','','','before','','Panamanian Balboa'),
				('PGK','3.12','','','before','','Papua New Guinean Kina'),
				('PKR','104.72','','','before','','Pakistani Rupee'),
				('PYG','5611.94','','','before','','Paraguayan Guarani'),
				('QAR','3.64','QAR','&#65020;','after','Unsure if this is correct','Qatari Rial'),
				('RON','3.92','lei','lei','before','','Romanian Leu'),
				('RUB','66.75','руб.','&#1088;&#1091;&#1073;','before','','Russian Ruble'),
				('RSD','107.69','','','before','','Serbian Dinar'),
				('RWF','773.47','','','before','','Rwandan Franc'),
				('SAR','3.75','SAR','&#65020;','after','Unsure if this is correct','Saudi Riyal'),
				('SEK','8.12','kr','kr','before','','Swedish Krona'),
				('SGD','1.35','$','&#36;','before','','Singapore Dollar'),
				('SBD','7.93','','','before','','Solomon Islands Dollar'),
				('SCR','13.50','','','before','','Seychellois Rupee'),
				('SDG','6.10','','','before','','Sudanese Pound'),
				('SHP','0.70','','','before','','St. Helena Pound'),
				('SLL','3975.00','','','before','','Sierra Leonean Leone'),
				('SOS','615.45','','','before','','Somali Shilling'),
				('SRD','5.37','','','before','','Surinamese Dollar'),
				('STD','21509.50','','','before','','São Tomé & Príncipe Dobra'),
				('SVC','8.73','','','before','','Salvadoran Colón'),
				('SYP','219.86','','','before','','Syrian Pound'),
				('SZL','14.71','','','before','','Swazi Lilangeni'),
				('SKK','22.24','','','before','','Slovak Koruna'),
				('THB','35.05','฿','&#322;','before','','Thai Baht'),
				('TRY','2.83','TL','TL','before','There is not a unicode','Turkish Lira'),
				('TTD','6.58','$','&#36;','before','','Trinidad & Tobago Dollar'),
				('TWD','32.39','$','&#36;','before','','New Taiwan Dollar'),
				('TJS','7.87','','','before','','Tajikistani Somoni'),
				('TMT','3.50','','','before','','Turkmenistani Manat'),
				('TND','2.0','','','before','','Tunisian Dinar'),
				('TOP','2.20','','','before','','Tongan Paʻanga'),
				('TZS','2183.75','','','before','','Tanzanian Shilling'),
				('USD','1.00','$','&#36;','before','','US Dollar'),
				('UAH','25.52','₴','&#8372;','before','','Ukrainian Hryvnia'),
				('UGX','3350.00','','','before','','Ugandan Shilling'),
				('UYU','31.00','','','before','','Uruguayan Peso'),
				('UZS','2882.68','','','before','','Uzbekistani Som'),
				('VEF','9.95','Bs F','Bs.','before','','Venezuelan Bolívar'),
				('VND','22292.50','₫','&#x20AB;','before','','Vietnamese Dong'),
				('VUV','109.61','','','before','','Vanuatu Vatu'),
				('WST','2.55','','','before','','Samoan Tala'),
				('XCD','2.70','$','&#36;','before','','East Caribbean Dollar'),
				('XAF','574.95','','','before','','Central African CFA Franc'),
				('XAG','0.05534047','','','before','','XAG'),
				('XAU','0.00079369','','','before','','XAU'),
				('XDR','0.71','','','before','','Special Drawing Rights'),
				('XOF','575.95','','','before','','West African CFA Franc'),
				('XPF','104.59','','','before','','CFP Franc'),
				('YER','249.50','','','before','','Yemeni Rial'),
				('ZAR','14.73','R','R','before','','South African Rand'),
				('ZMK','9674.99','','','before','','Zambian Kwacha'),
				('ZMW','9.67','','','before','','Zambian Kwacha'),
				('ZWL','361.90','','','before','','Zimbabwean Dollar')
			"""
        ),
    ]
