# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appinfo', '0003_auto_20160601_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appinfo',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
