import logging
import re

from decimal import Decimal

logger = logging.getLogger(__name__)

def parse(currencyStr):
  unicodeCurrencyStr = currencyStr if isinstance(currencyStr, unicode) \
      else currencyStr.decode('unicode-escape')
  m = re.match(r'([^\d]+)([\d]+)([,\.]?)([\d]+)', unicodeCurrencyStr)
  if not m:
    raise Exception('Could not parse currency string %s' % unicodeCurrencyStr)
  cstr, ipart, fpart = m.group(1), m.group(2), m.group(4)

  # The currency may be identified by a symbol or a currency code.
  if cstr in _CURRENCY_DESCRIPTIONS:
    curr = cstr
  elif cstr in _SYMBOL_MAP:
    curr = _SYMBOL_MAP[cstr]
  else:
    raise Exception('Unrecognized currency symbol or code %s' % cstr)

  amt = Decimal(ipart + '.' + fpart)
  return curr, amt


def convert_decimal_to_usd(amt, currencyStr):
  """
  Returns an equivalent decimal USD value for the given arguments.
  Returns None if the provided currencyStr argument is unrecognized.
  """
  rate = _DEFAULT_EXCHANGE_RATES['rates'].get(currencyStr, None)
  if rate is None:
    return None
  decimalRate = Decimal(str(rate))
  convertedAmt = amt / decimalRate
  return convertedAmt

def symbol_to_currency_code(unicodeSymbol):
  """
  Returns a three character currency code corresponding to the given unicode symbol.
  Note that this mapping is not well-defined, so reasonable defaults are chosen for
  overloaded symbols.
  """
  return _SYMBOL_MAP.get(unicodeSymbol, None)


# Retrieved 2015-01-20
_DEFAULT_EXCHANGE_RATES = {
    "base": "USD",
    "timestamp": 1422576061,
    "rates": {
		"AFA": 68.42,
        "AED": 3.67,
        "AFN": 68.42,
        "ALL": 121.70,
        "AOA": 162.76,
        "AMD": 482.61,
        "ANG": 1.79,
        "ARS": 14.47,
        "AUD": 1.32,
        "AWG": 1.79,
        "AZN": 1.53,
        "BHD": 0.38,
        "BDT": 78.10,
        "BBD": 2.00,
        "BYR": 19980.00,
        "BEF": 35.40,
        "BAM": 1.72,
        "BGN": 1.72,
        "BIF": 1567.30,
        "BMD": 1.00,
        "BND": 1.35,
        "BOB": 6.91,
        "BRL": 3.59,
        "BSD": 1.00,
        "BTC": 0.0024,
        "BTN": 66.44,
        "BWP": 10.95,
        "BZD": 2.00,
        "CAD": 1.30,
        "CDF": 928.00,
        "CHF": 0.95,
        "CLF": 0.03,
        "CLP": 682.75,
        "CNY": 6.47,
        "COP": 3097.15,
        "CRC": 535.37,
        "CUP": 26.50,
        "CVE": 97.289,
        "CZK": 23.72,
        "CUC": 1.00,
        "DJF": 177.69,
        "DKK": 6.53,
        "DOP": 45.91,
        "DZD": 108.08,
        "DEM": 1.72,
        "EEK": 11.73,
        "EGP": 8.88,
        "ERN": 16.18,
        "ETB": 21.50,
        "EUR": 0.88,
        "FJD": 2.09,
        "FKP": 0.66,
        "GBP": 0.70,
        "GEL": 2.27,
        "GMD": 42.61,
        "GHS": 3.82,
        "GIP": 0.69,
        "GID": 297.845,
        "GTQ": 7.73,
        "GNF": 7599.95,
        "GYD": 207.21,
        "HKD": 7.75,
        "HRK": 6.55,
        "HUF": 272.74,
        "HNL": 22.61,
        "HTG": 61.78,
        "IDR": 13110.00,
        "ILS": 3.77,
        "INR": 67.44,
        "IMP": 0.70,
        "IQD": 1107.10,
        "IRR": 30274.00,
        "ISK": 122.97,
        "ITL": 1709.66,
        "JOD": 0.71,
        "JEP": 0.70,
        "JPY": 108.05,
        "JMD": 121.70,
        "KES": 101.11,
        "KRW": 1143.88,
        "KWD": 0.30,
        "KYD": 0.82,
        "KGS": 69.98,
        "KHR": 4042.75,
        "KMF": 429.93,
        "KPW": 130.25,
        "KZT": 336.70,
        "LTL": 3.05,
        "LVL": 0.62,
        "LAK": 8115.45,
        "LBP": 1508.00,
        "LKR": 144.84,
        "LRD": 84.67,
        "LSL": 14.64,
        "LYD": 1.36,
        "MAD": 9.61,
        "MVR": 15.37,
        "MXN": 17.63,
        "MYR": 3.88,
        "MDL": 19.63,
        "MGA": 3171.45,
        "MKD": 53.81,
        "MMK": 1174.90,
        "MNT": 2019.50,
        "MOP": 7.99,
        "MRO": 290.4497,
        "MTL": 0.37,
        "MUR": 35.05,
        "MWK": 684.66,
        "MZN": 52.47,
        "MZM": 52479.80,
        "NGN": 199.05,
        "NOK": 8.20,
        "NZD": 1.46,
        "NAD": 14.71,
        "NIO": 28.31,
        "NPR": 106.32,
        "OMR": 0.39,
        "PEN": 3.28,
        "PHP": 46.11,
        "PLN": 3.74,
        "PAB": 1,
        "PGK": 3.12,
        "PKR": 104.72,
        "PYG": 5611.94,
        "QAR": 3.64,
        "RON": 3.92,
        "RUB": 66.75,
        "RSD": 107.69,
        "RWF": 773.47,
        "SAR": 3.75,
        "SEK": 8.12,
        "SGD": 1.35,
        "SBD": 7.93,
        "SCR": 13.50,
        "SDG": 6.10,
        "SHP": 0.70,
        "SLL": 3975.00,
        "SOS": 615.45,
        "SRD": 5.37,
        "STD": 21509.50,
        "SVC": 8.73,
        "SYP": 219.86,
        "SZL": 14.71,
        "SKK": 22.24,
        "TRY": 2.83,
        "THB": 35.05,
        "TTD": 6.58,
        "TWD": 32.39,
        "TJS": 7.87,
        "TMT": 3.50,
        "TND": 2.0,
        "TOP": 2.20,
        "TZS": 2183.75,
        "UAH": 25.52,
        "UGX": 3350.00,
        "USD": 1,
        "UYU": 31.00,
        "UZS": 2882.68,
        "VEF": 9.95,
        "VND": 22292.50,
        "VUV": 109.61,
        "WST": 2.55,
        "XAF": 574.95,
        "XAG": 0.05534047,
        "XAU": 0.00079369,
        "XCD": 2.70,
        "XDR": 0.71,
        "XOF": 574.95,
        "XPF": 104.59,
        "YER": 249.50,
        "ZAR": 14.73,
        "ZMK": 9674.99,
        "ZMW": 9.67,
        "ZWL": 361.90
    }
}

_CURRENCY_DESCRIPTIONS = {
    "AED": "United Arab Emirates Dirham",
    "AFN": "Afghan Afghani",
    "ALL": "Albanian Lek",
    "AMD": "Armenian Dram",
    "ANG": "Netherlands Antillean Guilder",
    "AOA": "Angolan Kwanza",
    "ARS": "Argentine Peso",
    "AUD": "Australian Dollar",
    "AWG": "Aruban Florin",
    "AZN": "Azerbaijani Manat",
    "BAM": "Bosnia-Herzegovina Convertible Mark",
    "BBD": "Barbadian Dollar",
    "BDT": "Bangladeshi Taka",
    "BGN": "Bulgarian Lev",
    "BHD": "Bahraini Dinar",
    "BIF": "Burundian Franc",
    "BMD": "Bermudan Dollar",
    "BND": "Brunei Dollar",
    "BOB": "Bolivian Boliviano",
    "BRL": "Brazilian Real",
    "BSD": "Bahamian Dollar",
    "BTC": "Bitcoin",
    "BTN": "Bhutanese Ngultrum",
    "BWP": "Botswanan Pula",
    "BYR": "Belarusian Ruble",
    "BZD": "Belize Dollar",
    "CAD": "Canadian Dollar",
    "CDF": "Congolese Franc",
    "CHF": "Swiss Franc",
    "CLF": "Chilean Unit of Account (UF)",
    "CLP": "Chilean Peso",
    "CNY": "Chinese Yuan",
    "COP": "Colombian Peso",
    "CRC": "Costa Rican Col\\u00f3n",
    "CUP": "Cuban Peso",
    "CVE": "Cape Verdean Escudo",
    "CZK": "Czech Republic Koruna",
    "DJF": "Djiboutian Franc",
    "DKK": "Danish Krone",
    "DOP": "Dominican Peso",
    "DZD": "Algerian Dinar",
    "EEK": "Estonian Kroon",
    "EGP": "Egyptian Pound",
    "ERN": "Eritrean Nakfa",
    "ETB": "Ethiopian Birr",
    "EUR": "Euro",
    "FJD": "Fijian Dollar",
    "FKP": "Falkland Islands Pound",
    "GBP": "British Pound Sterling",
    "GEL": "Georgian Lari",
    "GGP": "Guernsey Pound",
    "GHS": "Ghanaian Cedi",
    "GIP": "Gibraltar Pound",
    "GMD": "Gambian Dalasi",
    "GNF": "Guinean Franc",
    "GTQ": "Guatemalan Quetzal",
    "GYD": "Guyanaese Dollar",
    "HKD": "Hong Kong Dollar",
    "HNL": "Honduran Lempira",
    "HRK": "Croatian Kuna",
    "HTG": "Haitian Gourde",
    "HUF": "Hungarian Forint",
    "IDR": "Indonesian Rupiah",
    "ILS": "Israeli New Sheqel",
    "IMP": "Manx pound",
    "INR": "Indian Rupee",
    "IQD": "Iraqi Dinar",
    "IRR": "Iranian Rial",
    "ISK": "Icelandic Kr\\u00f3na",
    "JEP": "Jersey Pound",
    "JMD": "Jamaican Dollar",
    "JOD": "Jordanian Dinar",
    "JPY": "Japanese Yen",
    "KES": "Kenyan Shilling",
    "KGS": "Kyrgystani Som",
    "KHR": "Cambodian Riel",
    "KMF": "Comorian Franc",
    "KPW": "North Korean Won",
    "KRW": "South Korean Won",
    "KWD": "Kuwaiti Dinar",
    "KYD": "Cayman Islands Dollar",
    "KZT": "Kazakhstani Tenge",
    "LAK": "Laotian Kip",
    "LBP": "Lebanese Pound",
    "LKR": "Sri Lankan Rupee",
    "LRD": "Liberian Dollar",
    "LSL": "Lesotho Loti",
    "LTL": "Lithuanian Litas",
    "LVL": "Latvian Lats",
    "LYD": "Libyan Dinar",
    "MAD": "Moroccan Dirham",
    "MDL": "Moldovan Leu",
    "MGA": "Malagasy Ariary",
    "MKD": "Macedonian Denar",
    "MMK": "Myanma Kyat",
    "MNT": "Mongolian Tugrik",
    "MOP": "Macanese Pataca",
    "MRO": "Mauritanian Ouguiya",
    "MTL": "Maltese Lira",
    "MUR": "Mauritian Rupee",
    "MVR": "Maldivian Rufiyaa",
    "MWK": "Malawian Kwacha",
    "MXN": "Mexican Peso",
    "MYR": "Malaysian Ringgit",
    "MZN": "Mozambican Metical",
    "NAD": "Namibian Dollar",
    "NGN": "Nigerian Naira",
    "NIO": "Nicaraguan C\\u00f3rdoba",
    "NOK": "Norwegian Krone",
    "NPR": "Nepalese Rupee",
    "NZD": "New Zealand Dollar",
    "OMR": "Omani Rial",
    "PAB": "Panamanian Balboa",
    "PEN": "Peruvian Nuevo Sol",
    "PGK": "Papua New Guinean Kina",
    "PHP": "Philippine Peso",
    "PKR": "Pakistani Rupee",
    "PLN": "Polish Zloty",
    "PYG": "Paraguayan Guarani",
    "QAR": "Qatari Rial",
    "RON": "Romanian Leu",
    "RSD": "Serbian Dinar",
    "RUB": "Russian Ruble",
    "RWF": "Rwandan Franc",
    "SAR": "Saudi Riyal",
    "SBD": "Solomon Islands Dollar",
    "SCR": "Seychellois Rupee",
    "SDG": "Sudanese Pound",
    "SEK": "Swedish Krona",
    "SGD": "Singapore Dollar",
    "SHP": "Saint Helena Pound",
    "SLL": "Sierra Leonean Leone",
    "SOS": "Somali Shilling",
    "SRD": "Surinamese Dollar",
    "STD": "S\\u00e3o Tom\\u00e9 and Pr\\u00edncipe Dobra",
    "SVC": "Salvadoran Col\\u00f3n",
    "SYP": "Syrian Pound",
    "SZL": "Swazi Lilangeni",
    "THB": "Thai Baht",
    "TJS": "Tajikistani Somoni",
    "TMT": "Turkmenistani Manat",
    "TND": "Tunisian Dinar",
    "TOP": "Tongan Pa\\u02bbanga",
    "TRY": "Turkish Lira",
    "TTD": "Trinidad and Tobago Dollar",
    "TWD": "New Taiwan Dollar",
    "TZS": "Tanzanian Shilling",
    "UAH": "Ukrainian Hryvnia",
    "UGX": "Ugandan Shilling",
    "USD": "United States Dollar",
    "UYU": "Uruguayan Peso",
    "UZS": "Uzbekistan Som",
    "VEF": "Venezuelan Bol\\u00edvar Fuerte",
    "VND": "Vietnamese Dong",
    "VUV": "Vanuatu Vatu",
    "WST": "Samoan Tala",
    "XAF": "CFA Franc BEAC",
    "XAG": "Silver (troy ounce)",
    "XAU": "Gold (troy ounce)",
    "XCD": "East Caribbean Dollar",
    "XDR": "Special Drawing Rights",
    "XOF": "CFA Franc BCEAO",
    "XPF": "CFP Franc",
    "YER": "Yemeni Rial",
    "ZAR": "South African Rand",
    "ZMK": "Zambian Kwacha (pre-2013)",
    "ZMW": "Zambian Kwacha",
    "ZWL": "Zimbabwean Dollar"
}

# This map provides reasonable default currency codes for a given currency symbol.
# Note that many currencies may share a single symbol, so correctness cannot be guaranteed.
_SYMBOL_MAP = {
    u'\u0024': 'USD',  # Also ARS, AUD, BBD, BMD, BND, BSD, CAD, CLP, COP, FJD, GYD, HKD, KYD, LRD, MXN, NAD, NZD, SBD, SGD, SRD, SVC, TVD, XCD
    u'\u0050': 'BWP',
    u'\u0046\u0074': 'HUF',
    u'\u060B': 'AFN',
    u'\u006B\u0072': 'SEK',  # Also DKK, EEK, ISK, NOK, SEK
    u'\u0043\u0048\u0046': 'CHF',
    u'\u004B\u004D': 'BAM',
    u'\u0043\u0024': 'NIO',
    u'\u0052\u0024': 'BRL',
    u'\u006C\u0065\u0069': 'RON',
    u'\u20A9': 'KRW',  # Also KPW
    u'\u007A\u0142': 'PLN',
    u'\u004C\u0073': 'LVL',
    u'\u0053\u002F\u002E': 'PEN',
    u'\u004D\u0054': 'MZN',
    u'\u00A5': 'JPY',  # Also CNY
    u'\u0042\u0073': 'VEF',
    u'\u043C\u0430\u043D': 'AZN',
    u'\u004A\u0024': 'JMD',
    u'\u0024\u0062': 'BOB',
    u'\u0024\u0055': 'UYU',
    u'\u0051': 'GTQ',
    u'\u20AC': 'EUR',
    u'\u0440\u0443\u0431': 'RUB',
    u'\u20AA': 'ILS',
    u'\uFDFC': 'SAR',  # Also IRR, OMR, QAR, YER
    u'\u006B\u006E': 'HRK',
    u'\u00A3': 'GBP',  # Also EGP, FKP, GGP, GIP, IMP, JEP, LBP, SHP, SYP
    u'\u0052\u004D': 'MYR',
    u'\u0047\u0073': 'PYG',
    u'\u20B4': 'UAH',
    u'\u004C\u0065\u006B': 'ALL',
    u'\u20A4': 'TRL',
    u'\u0052': 'ZAR',
    u'\u0E3F': 'THB',
    u'\u0054\u0054\u0024': 'TTD',
    u'\u0052\u0070': 'IDR',
    u'\u0053': 'SOS',
    u'\u20A1': 'CRC',
    u'\u20AE': 'MNT',
    u'\u0052\u0044\u0024': 'DOP',
    u'\u0192': 'ANG',  # Also AWG
    u'\u004C': 'HNL',
    u'\u20B1': 'PHP',  # Also CUP
    u'\u20AD': 'LAK',
    u'\u0042\u005A\u0024': 'BZD',
    u'\u043B\u0432': 'BGN',  # Also KGS, KZT, UZS
    u'\u00A2': 'GHC',
    u'\u0434\u0435\u043D': 'MKD',
    u'\u004C\u0074': 'LTL',
    u'\u20A8': 'MUR',  # Also LKR, NPR, PKR, SCR
    u'\u0070\u002E': 'BYR',
    u'\u17DB': 'KHR',
    u'\u20AB': 'VND',
    u'\u004E\u0054\u0024': 'TWD',
    u'\u004B\u010D': 'CZK',
    u'\u20A6': 'NGN',
    u'\u005A\u0024': 'ZWD',
    u'\u0414\u0438\u043D\u002E': 'RSD',
    u'\u0042\u002F\u002E': 'PAB',
}
