# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-14 05:03
from __future__ import unicode_literals

import core.customfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerexternallogininfo',
            name='password',
            field=core.customfields.EncryptedCharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='customerexternallogininfo',
            name='username',
            field=core.customfields.EncryptedCharField(max_length=256),
        ),
    ]
